services:
  singularity:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: singularity_core
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    env_file: ./config/.env
    command: python3 -m core.dashboard
    environment:
      - TZ=Europe/Madrid
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      # --- 1. CONFIGURACIÓN ---
      - ./config/.env:/app/.env:z
      - ./config/singularity_config.py:/app/singularity_config.py:z
      - ./config/config.py:/app/RawLoadrr/data/config.py:z
      - ./config/mass_config.py:/app/extras/MASS-EDITION-UNIT3D/config.py:z

      # --- 2. WORK DATA & PERSISTENCIA ---
      - ./work_data/mass_editor/ids.txt:/app/extras/MASS-EDITION-UNIT3D/ids.txt:z
      - ./work_data/mass_editor/completados.txt:/app/extras/MASS-EDITION-UNIT3D/completados.txt:z
      - ./work_data/mass_editor/completados_img.txt:/app/extras/MASS-EDITION-UNIT3D/completados_img.txt:z
      - ./work_data/mass_editor/mapeo_maestro.json:/app/extras/MASS-EDITION-UNIT3D/mapeo_maestro.json:z
      - ./work_data/mass_editor/titulos_mapa.json:/app/extras/MASS-EDITION-UNIT3D/titulos_mapa.json:z
      - ./work_data/mass_editor/mapeo_por_titulo.json:/app/extras/MASS-EDITION-UNIT3D/mapeo_por_titulo.json:z
      - ./work_data/tmp:/app/RawLoadrr/tmp:z
      - ./work_data/logs:/app/logs:z
      - ./work_data/reports:/app/MKVerything/docs:z
      - ./work_data/trackers:/app/RawLoadrr/src/trackers:z
      - ./work_data/reports:/app/work_data/reports:z

      # --- 3. PERSISTENCIA DE MÓDULOS ---
      - ./work_data/logs/csi_log:/app/extras/CSI/csi_log:z
      - ./work_data/cookies:/app/RawLoadrr/data/cookies:z
      - ./work_data/logs/rawloadrr:/app/RawLoadrr/logs:z
      - ./work_data/logs/mkverything:/app/MKVerything/logs:z
      - ./work_data/qbit_backup:/app/RawLoadrr/qbit_backup:z

      # --- 4. EL ARSENAL ---
      - /mnt/armagedon_data/data:/data:z
      - /mnt/armagedon/data:/cfg_data:z

    network_mode: host
    stdin_open: true
    tty: true
